### ISSUE TITLE
Game Crashes when opening Belt or Blade UI (Fabric 1.20.1)

### ISSUE THREAD

**Issue by ElRokur** [Traverse-Joe/HeartyTrinkets#3]
Title says it all, 

Game crashes when trying to open the Belt or Blade UI, hope you can fix it :)

[latest.log](https://github.com/Traverse-Joe/HeartyTrinkets/files/14625473/latest.log)

**Comment by Traverse-Joe** [comment]
I am uploading a new version of for 1.20.1 as there is a slight change in 1.20.2 with rendering I will have it posted shortly
